### ISSUE TITLE
Multi select initial load only loads first association on edit

### ISSUE THREAD

**Issue by joelrojo** [holyketzer/activeadmin-ajax_filter#39]
Hi, I'm having trouble getting all the data for a specific field on initial load.

I'm using `acts_as_taggable_on` gem to associate an object with multiple tags, but can't seem to get all tags that are associated with an exsiting object to load when on edit. 

It only loads the first tag in the form. Works great on new objects or objects with empty or just one tag.

```ruby
f.input :tags,
  input_html: { class: "default-select" },
  collection: [],
  as: :ajax_select,
  data: {
    url: filter_admin_tags_path,
    search_fields: [:name],
    display_fields: [:name]
  }
```

Any suggestions?

**Comment by joelrojo** [comment]
@holyketzer any ideas on this one? 

Still haven't been able to figure it out with the all the many to many relationships I have in my db.

**Comment by holyketzer** [comment]
@joelrojo  Sorry I didn't check it yet, I plan to investigate it this week.

**Comment by joelrojo** [comment]
@holyketzer tried to do some more digging today, but still can't seem to find a solution. Any suggestions on where I should investigate further?

Works great so far when I add multiple items from the select and save (on all other HABTM associations as well), just the small issue when it loads the edit form it only pulls the first object from the associated collection. 

I end up having re-add the same tags or objects in the select if I want to update any other fields, otherwise it just saves with the first object and removes the other associations.

`filter?q%5Bid_eq%5D=1%201%20158%20136&limit=5&order=name%20ASC` is the filter url being called on loading the form

**Comment by holyketzer** [comment]
@joelrojo I fixed it, fix now in master

**Comment by joelrojo** [comment]
I tried installing from master, but still not working for me. The initial load is still `filter?q%5Bid_eq%5D=1%201%20158%20136&limit=5&order=name%20ASC` and is only returning the first result. Search is working well though, just not initial load:

<img width="285" alt="Screen Shot 2020-04-23 at 12 02 19 PM" src="https://user-images.githubusercontent.com/217719/80138929-771a8900-855a-11ea-9b1a-c2480a7bdba2.png">

The regular `f.input :users` is on top, while this is the code for the bottom inut:

```ruby
f.input :users,
    input_html: { class: "default-select" },
    collection: [],
    as: :ajax_select,
    data: {
      url: filter_admin_users_path,
      search_fields: [:name, :username],
      display_fields: [:name, :username]
    }
```

`.users` are a HABTM assocation on the model: `has_and_belongs_to_many :users`

**Comment by holyketzer** [comment]
@joelrojo looks like it 's some assets caching issue because there is should be `id_in` filter instead of `id_eq` let me release the new version of gem

**Comment by joelrojo** [comment]
@holyketzer Awesome, it works now. That was definitely it. Thanks a lot!

**Comment by holyketzer** [comment]
Cool! You are welcome )
